### ISSUE TITLE
change name of the tab

### ISSUE THREAD

**Issue by pritipsingh** [pritipsingh/The-Productive-Champion#27] opened 2024-04-16 16:45 UTC
Something like Twitter| Focus Mode & disable notifications

![Screenshot 2024-04-16 at 10 14 35 PM](https://github.com/pritipsingh/The-Productive-Champion/assets/85965351/eb5d1e83-e0d2-45e9-94f3-8c948323a0ac)

**Comment by ahsanfarooq210** [comment] 2024-05-08 02:50
hi @pritipsingh. I would like to work on this issue. Please assign this to me

**Comment by ahsanfarooq210** [comment] 2024-05-08 17:57
Hi @pritipsingh What we can do is we can append "| Focus Mode & disable notifications" in front of the tab name of the website that the user has opened and is blocked by the user. Will that work for us?

**Comment by ahsanfarooq210** [comment] 2024-05-09 16:15
Hey. I noticed that in the main branch, the UI went blank when I clicked the Edit Website Button 

![image](https://github.com/pritipsingh/The-Productive-Champion/assets/61400176/736b4836-2a47-4588-927d-b8f5ed9992f1)


now in the `WebsiteEditPage.tsx` there was some code that was changed when compared to the deployed version of the extension on the Chrome web store

### in the main branch


  useEffect(() => {
    // Load saved list from local storage or use the hardcoded list if none is found
    const savedItems = JSON.parse(localStorage.getItem('alreadyBlockedWebsites')!);
    if (savedItems && savedItems.length > 0) {
      setSlreadyBlockedWebsitesSet(savedItems);
    } else if(savedItems.length === 0 && hasOpened === false) {
      setSlreadyBlockedWebsitesSet(alreadyBlockedWebsites as any);
      setHasOpened(true)
    }else if(savedItems.length === 0 && hasOpened === true) {
      setSlreadyBlockedWebsitesSet([])
    }
  }, []);


now the above code causes issue because in the local storage, we do not have **alreadyBlockedWebsites** initially so this comes as null and it throws an error of undefined.

### and In the deployed version



  useEffect(() => {
    // Attempt to load the list from local storage
    let savedItems;
    try {
      const item = localStorage.getItem("alreadyBlockedWebsites");
      savedItems = item ? JSON.parse(item) : null;
    } catch (error) {
      console.error("Error parsing alreadyBlockedWebsites from localStorage:", error);
      savedItems = null;
    }
    if (savedItems && savedItems.length > 0) {
      // If savedItems exists and has items, use it
      setSlreadyBlockedWebsitesSet(savedItems);
    } else {
      // If savedItems is null, empty, or parsing failed
      if (hasOpened) {
        // If the app has been opened before, set to an empty array
        setSlreadyBlockedWebsitesSet([]);
      } else {
        // If the app has not been opened before, use the hardcoded list and mark as opened
        setSlreadyBlockedWebsitesSet(alreadyBlockedWebsites); // Assuming 'alreadyBlockedWebsites' is an array
        setHasOpened(true); // This marks the initial setup as done
      }
    }
  }, []);  

are there any code changes that are not in the main branch

**Comment by ahsanfarooq210** [comment] 2024-05-10 18:41
I am having an issue with infinite component re-rendering. when ever I change the document title in the Restrict component, the component starts to render infinitely. Please help

**Comment by pritipsingh** [comment] 2024-05-14 18:45
Hey @ahsanfarooq210 I am sorry all the notifications were in spam for some reasons. I saw them just now! Lemme try to reproduce this

**Comment by ahsanfarooq210** [comment] 2024-05-18 14:15
Hi @pritipsingh. Were you able to reproduce this issue?

**Closed as completed** 2024-07-20 09:14 UTC
Labels: help wanted, good first issue
